version: '3.8'
services:
  node:
    container_name: frontend_react
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "3000:5173"
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend:/app